Smart Pointers, Complete
No more calls to delete! Smart pointers in use almost everywhere.
Exception: still (intentionally) using raw pointers instead of smart
pointers for SDL stuff. May decide to wrap those in smart pointers later
as well.